### ISSUE TITLE
Problem with HTML entiy parsing

### ISSUE THREAD

**Issue by jkphl** [thephpleague/commonmark#206] opened 2015-11-16 20:31 UTC
The parser seems to have a problem with HTML entity detection / handling. Example:

```php
$environment = \League\CommonMark\Environment::createCommonMarkEnvironment();
$parser = new \League\CommonMark\DocParser($environment);
$renderer = new \League\CommonMark\HtmlRenderer($environment);

echo $renderer->renderBlock($parser->parse(
    "If you want to write about 'AT&T', you need to write '`AT&amp;T`'."
));
```

results in

```html
<p>If you want to write about 'AT&amp;T`'.</p>
```

Half of the sentence is swallowed, probably due to the parser interpreting the first `&T` as the start of an (invalid) HTML entity I guess‽

**Comment by colinodell** [comment] 2015-11-16 22:45
This is likely a duplicate of #192.  Basically the `EntityParser` would "eat" everything between the first `&` and the last HTML entity.

[Version 0.12](https://github.com/thephpleague/commonmark/releases/tag/0.12.0) contains a fix for this issue, so please upgrade to this version.  ([This Babelmark 2 test](http://johnmacfarlane.net/babelmark2/?normalize=1&text=If+you+want+to+write+about+%27AT%26T%27%2C+you+need+to+write+%27%60AT%26amp%3BT%60%27.)  shows that 0.12 behaves as expected given your input).

**Closed by colinodell** 2015-11-16 22:45 UTC

**Comment by jkphl** [comment] 2015-11-17 08:19
You're right, updating to 0.12 fixed it — I somehow missed that latest release. Thank you! :)
