### ISSUE TITLE
HTML entities issue?

### ISSUE THREAD

**Issue by mnapoli** [thephpleague/commonmark#252] opened 2016-06-27 20:25 UTC
Hi there!

Here is something that is causing weird rendering in my application:

```
> and the test:
>
> <?php
> ini_set("pcntl.async_signals", "1");

We use 2/3 vote for "a feature affecting the language itself".
```

Here is the output I get:

```
<p>and the test:</p>
<blockquote>
<?php
ini_set("pcntl.async_signals", "1");
</blockquote>
<p>We use 2/3 vote for &quot;a feature affecting the language itself&quot;.</p>
```

Here is the one I would expect:

```
<p>and the test:</p>
<blockquote>
&gt;?php
ini_set(&quot;pcntl.async_signals&quot;, &quot;1&quot;);
</blockquote>
<p>We use 2/3 vote for &quot;a feature affecting the language itself&quot;.</p>
```

The diff:

```diff
<p>and the test:</p>
 <blockquote>
-&gt;?php
-ini_set(&quot;pcntl.async_signals&quot;, &quot;1&quot;);
+<?php
+ini_set("pcntl.async_signals", "1");
 </blockquote>
 <p>We use 2/3 vote for &quot;a feature affecting the language itself&quot;.</p>
```

Is there a reason why HTML entities are not encoded in quotes?

The main problem I'm having (beyond "correctness") is that `<?php` causes the HTML to be wrongly interpreted by web browsers.

By the way thanks for the awesome library!

**Comment by colinodell** [comment] 2016-06-27 21:30
Thanks for reporting this issue!

[The JS reference parser exhibits this same issue](http://spec.commonmark.org/dingus/?text=%3E%20and%20the%20test%3A%0A%3E%0A%3E%20%3C%3Fphp%0A%3E%20ini_set(%22pcntl.async_signals%22%2C%20%221%22)%3B%0A%0AWe%20use%202%2F3%20vote%20for%20%22a%20feature%20affecting%20the%20language%20itself%22.).  Essentially, `<?php` and the following line are being parsed as raw HTML.  [According to the current spec](http://spec.commonmark.org/0.25/#html-blocks), it seems that HTML inside of blockquotes should indeed be parsed this way.

(Interestingly enough, based on how the spec is written, I think the very last line outside the blockquote is supposed to be included as raw HTML, which would be really strange.)

I do agree with you - this behavior doesn't seem ideal.  I've therefore reported this issue to the maintainer of the spec and reference parser: https://github.com/jgm/commonmark.js/issues/103  I'm going to wait for a response before making any changes to ensure that whatever solution we implement aligns with what's going on upstream.

**Comment by mnapoli** [comment] 2016-06-27 21:32
Thank you!

**Comment by colinodell** [comment] 2016-06-28 18:23
Discussion of parsing `<?php` as HTML has been moved here: https://talk.commonmark.org/t/type-3-html-blocks/2135/3

**Comment by colinodell** [comment] 2016-07-02 19:17
According to the spec authors, this behavior is not a bug.  I'm therefore going to close this issue.

**Closed by colinodell** 2016-07-02 19:17 UTC
Labels: bug, on hold, spec-compliance
