### ISSUE TITLE
TOC crashes with underline-generated headings

### ISSUE THREAD

**Issue by majenkotech** [thephpleague/commonmark#579] opened 2020-10-17 19:11 UTC
**Version(s) affected**: 1.5.5

**Description**  
TableOfContents Extension crashes with titles created using underlines with:

```
Return value of League\CommonMark\Block\Element\AbstractBlock::getStartLine() must be of the type int, null returned (View: /var/www/html/uecide/resources/views/library.blade.php)
```

**How to reproduce**  

Use the TOC extension with headings created using underlines:

```
This is a top level
==================

This is another level
---------------------
```

**Possible Solution**  

**Additional context**  

I am using CommonMark in Laravel 8 with a wrapper `graham-campbell/markdown`.

Full trace:

```
Facade\Ignition\Exceptions\ViewException: Return value of League\CommonMark\Block\Element\AbstractBlock::getStartLine() must be of the type int, null returned (View: /var/www/html/uecide/resources/views/library.blade.php) in file /var/www/html/uecide/vendor/league/commonmark/src/Block/Element/AbstractBlock.php on line 123

#0 /var/www/html/uecide/vendor/league/commonmark/src/Extension/TableOfContents/TableOfContentsGenerator.php(79): League\CommonMark\Block\Element\AbstractBlock->getStartLine()
#1 /var/www/html/uecide/vendor/league/commonmark/src/Extension/TableOfContents/TableOfContentsBuilder.php(69): League\CommonMark\Extension\TableOfContents\TableOfContentsGenerator->generate()
#2 /var/www/html/uecide/vendor/league/commonmark/src/Environment.php(359): League\CommonMark\Extension\TableOfContents\TableOfContentsBuilder->onDocumentParsed()
#3 /var/www/html/uecide/vendor/league/commonmark/src/DocParser.php(82): League\CommonMark\Environment->dispatch()
#4 /var/www/html/uecide/vendor/league/commonmark/src/Converter.php(64): League\CommonMark\DocParser->parse()
#5 /var/www/html/uecide/vendor/graham-campbell/markdown/src/View/Directive/MarkdownDirective.php(53): League\CommonMark\Converter->convertToHtml()
#6 /var/www/html/uecide/resources/views/library.blade.php(8): GrahamCampbell\Markdown\View\Directive\MarkdownDirective->render()
#7 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/html/u...')
#8 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#9 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#10 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#11 /var/www/html/uecide/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\View\Engines\CompilerEngine->get()
#12 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\Ignition\Views\Engines\CompilerEngine->get()
#13 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getContents()
#14 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#15 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Http/Response.php(62): Illuminate\View\View->render()
#16 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\Http\Response->setContent()
#17 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Routing/Router.php(765): Illuminate\Http\Response->__construct()
#18 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router::toResponse()
#19 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\Routing\Router->prepareResponse()
#20 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#23 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#25 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#27 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#29 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#30 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#32 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#34 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Pipeline\Pipeline->then()
#36 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\Routing\Router->runRouteWithinStack()
#37 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\Routing\Router->runRoute()
#38 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->dispatchToRoute()
#39 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch()
#40 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#41 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#43 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#45 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#47 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#49 /var/www/html/uecide/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#51 /var/www/html/uecide/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#53 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then()
#55 /var/www/html/uecide/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#56 /var/www/html/uecide/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#57 {main}
```

**Comment by colinodell** [comment] 2020-10-17 19:43
Looks like there's an issue with tracking the start/end line for some of the blocks.  This should be a fairly straight-forward fix - just need to check where/why those aren't being set.

**Comment by thicolares** [comment] 2020-10-17 20:57
I can try to reproduce it on my local and send a PR

**Comment by colinodell** [comment] 2020-10-17 21:24
Sorry, I should have updated this issue to reflect that I've begun working on a fix.

In a nutshell, the start and end lines are supposed to be set automatically during parsing.  The setext headings were not getting this value set, and therefore the Table of Contents was failing to read this value.

I think we ultimately need to make two changes here:

1. Fix replacement blocks not inheriting the start/end lines of the container they are replacing (the underlying bug here)
2. Default all blocks to have their start and end lines set to `0`.  This would address some other instances where dynamically-added blocks are being added after parsing has completed which don't necessarily correspond to a particular line number.  `0` will avoid similar issues with those blocks in `1.x` and we can look at making these values nullable in `2.x`.

**Comment by colinodell** [comment] 2020-10-17 21:35
[Version 1.5.6](https://github.com/thephpleague/commonmark/releases/tag/1.5.6) has been released with a fix for this issue.  Thanks for reporting it!

**Closed by colinodell** 2020-10-17 21:35 UTC
Labels: bug

**Comment by majenkotech** [comment] 2020-10-17 22:00
Confirm fixed. Thanks for such rapid attention :)
