### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by ntzm** [thephpleague/commonmark#401] opened 2020-01-14 22:42 UTC
**Version(s) affected**: 1.2.0

**Description**  

When parsing text with certain characters, I get: `Invalid argument supplied for foreach() in /src/Cursor.php on line 256`

**How to reproduce**  

```
<?php

require __DIR__ . '/vendor/autoload.php';

$converter = new \League\CommonMark\CommonMarkConverter();

$converter->convertToHtml("\x09\xca\xca");
```

**Comment by GrahamCampbell** [comment] 2020-01-15 00:35
It looks like this is a bug in PHP: https://3v4l.org/ZTcal.

**Comment by colinodell** [comment] 2020-01-15 02:28
`\x09\xca\xca` is not valid UTF-8:  https://3v4l.org/M2cB1  This library is only compatible with UTF-8 and ASCII encodings.  If you're using something else, please be sure to convert it to UTF-8 first.

The behavior you're seeing is caused by the fix to https://bugs.php.net/bug.php?id=76127 which landed in PHP 7.3.5.  (Thanks to Graham for helping me look at PHP as the potential culprit here)

I'm on the fence as to whether this library should try validating the encoding of the given Markdown prior to trying to parse it, or if we should continue relying on developers to do that themselves.

**Comment by ntzm** [comment] 2020-01-15 08:53
Understood, although I think most people who use this library won't know to convert it to UTF-8 first.

**Comment by colinodell** [comment] 2020-01-16 01:25
We do have a warning immediately below the first example in the README.

Given that this library can already potentially throw a `\RuntimeException` in some edge cases, I think it would be reasonable to add a quick `mb_check_encoding()` check inside of `DocParser::parse()` and throw a `\RuntimeException` is an invalid encoding is found.

**Closed** 2020-01-16 03:13 UTC
