### ISSUE TITLE
Renderer for parent classes don't get called

### ISSUE THREAD

**Issue by marijnvdwerf** [thephpleague/commonmark#209] opened 2015-12-02 00:52 UTC
When I extend `Html` with a new class (`OpenTag`), and add an object to the document, the `HtmlRenderer` throws an exception:

```
Unable to find corresponding renderer for inline type OneMoreThing\CommonMark\Sanitize\Nodes\OpenTag
```

I would expect the renderer of the parent class to be called.

**Comment by colinodell** [comment] 2015-12-02 02:09
Renderers must currently be set for each specific class:

```php
    /**
     * @param string                 $blockClass
     * @param BlockRendererInterface $blockRenderer
     *
     * @return $this
     */
    public function addBlockRenderer($blockClass, BlockRendererInterface $blockRenderer)
```

Your expectation makes sense though, so I think this would be a worthwhile feature to add.

Perhaps the easiest and most-efficient implementation would be modifying the `getBlockRenderer` method from this:

```php
    /**
     * @param string $blockClass
     *
     * @return BlockRendererInterface|null
     */
    public function getBlockRendererForClass($blockClass)
    {
        $this->initializeExtensions();
        if (!isset($this->blockRenderersByClass[$blockClass])) {
            return;
        }
        return $this->blockRenderersByClass[$blockClass];
    }
```

To something like this:

```php
    /**
     * @param string $blockClass
     *
     * @return BlockRendererInterface|null
     */
    public function getBlockRendererForClass($blockClass)
    {
        $this->initializeExtensions();
        if (isset($this->blockRenderersByClass[$blockClass])) {
            return $this->blockRenderersByClass[$blockClass];
        }

        // No renderer was found for this specific type
        // Maybe we registered one for its parent?
        foreach ($this->blockRenderersByClass as $class => $renderer) {
            if (is_subclass_of($blockClass, $class)) {
                // "Cache" this result to avoid future loops
                $this->blockRenderersByClass[$blockClass] = $renderer;

                return $renderer
        }

        return;
    }
```

The same thing would apply to inline renderers too.

Thoughts?

**Comment by marijnvdwerf** [comment] 2015-12-02 07:03
I'd rater use `get_parent_class` on the item to be rendered. That way the definition order of renderers doesn't matter.

**Comment by colinodell** [comment] 2016-01-12 23:04
This is somewhat related to #35

**Comment by colinodell** [comment] 2016-01-14 04:26
#210 means that the definition order **does** matter now.  However, I do think it may be best to recursively check `get_parent_class` instead of the solution I proposed above.  That'll allow the first, most-specific renderer to be returned.

For example, let's say we had this inheritance tree for `Link` nodes:

* `Link`
  * `ShortLink`
    * `BitlyLink`

And parsers defined in this order:

* `LinkRenderer`
* `ShortLinkRenderer`

Which one should be used when a `BitlyLink` needs to be rendered?  According to my original suggestion, `LinkRenderer` would "win", even though its not the "most-specific" one.

So we should instead do something like this (totally untested code):

~~~php
for ($parent = $blockClass; $parent; $parent = get_parent_class($parent)) {
    if (!isset($this->blockRenderersByClass[$parent])) {
        continue;
    }

    $renderer = $this->blockRenderersByClass[$parent]

    // "Cache" this result to avoid future loops
    $this->blockRenderersByClass[$blockClass] = $renderer;

    return $renderer;
}
~~~

(I hope this makes sense)

**Comment by marijnvdwerf** [comment] 2016-01-15 10:38
Looks okay to me

**Comment by colinodell** [comment] 2017-10-26 01:38
@marijnvdwerf Do you still need this feature?  If so, could you please take a look at #209 and let me know if that fits your needs?  If not I might close this and #209 out to help reduce the backlog :)  Thanks!

**Comment by colinodell** [comment] 2018-09-18 12:54
It has been over two years since this was requested, and nobody else has confirmed needing this feature, so I'm going to close this issue.  I will gladly re-open this in the future if anyone expresses interest.

**Closed** 2020-04-13 15:58 UTC
Labels: enhancement, feedback wanted
