### ISSUE TITLE
Autolink extension breaks some URLs too early

### ISSUE THREAD

**Issue by inguin** [thephpleague/commonmark#492] opened 2020-06-03 08:18 UTC
**Version(s) affected**: 1.5

**Description**  
The autolink extension breaks certain URLs too early. We have a Wiki system that uses URLs like `http://wiki/Puncutation_in_links:_why_its_bad_(and_should_be_avoided)`. The markdown parser recognizes the part between the colon and the opening parenthesis as emphasized text. The autolink extension only sees the node with the URL up to the colon.

**How to reproduce**  
```php
$environment = \League\CommonMark\Environment::createCommonMarkEnvironment();
$environment->addExtension(new \League\CommonMark\Extension\Autolink\AutolinkExtension());
$converter = new \League\CommonMark\CommonMarkConverter([], $environment);
echo $converter->convertToHtml('http://wiki/Punctuation_in_links:_why_its_bad_(and_should_be_avoided)');
```

**Possible Solution**  
Not sure if there's an easy fix. I assume the autolink processor could somehow merge subsequent nodes as long as the regex consumes everything.

**Comment by colinodell** [comment] 2020-06-03 13:02
Yeah, the challenge is that auto-link parsing happens at the very end of the parsing step, where the AST looks something like this before the autolink extension gets it:

```xml
<document>
  <paragraph>
    <text>http://wiki/Puncutation_in_links:</text>
    <emph>
      <text>why_its_bad</text>
    </emph>
    <text>(and_should_be_avoided)</text>
  </paragraph>
</document>
```

The emphasized text could have been created with underscores or asterisks, but we no longer have that information at this point.  We'd probably have to check for links much earlier during the parsing step which would be a significant change, and likely not something we could do within the 1.x branch, but we could investigate a possible solution in 2.0.


----

For what it's worth, we're not the only ones with this problem: https://babelmark.github.io/?text=http%3A%2F%2Fwiki%2FPuncutation_in_links%3A_why_its_bad_(and_should_be_avoided)

**Comment by markcarver** [comment] 2020-06-03 13:22
It seems to be working with native GFM (which the extension is based on).

Maybe a temporary solution in 1.x could be to create a separate parser that runs much earlier to extract links and replace them with temporary placeholders to be replaced at a later time?

**Comment by colinodell** [comment] 2020-06-03 13:43
We could add an inline parser that looks for `w` or `h` (since URL autolinks must start with `www` or `http`), but that would have some major performance impacts since the parser would stop at every single `w` and `h` character it sees (most of which would not be autolinks).

Some other potential ways of addressing this:

## Revise inline parsing in 2.0

Instead of each parser giving an array of characters they're interested in, we could instead allow them to provide a list of strings.  These could be either single characters or longer strings like `www.`, `http://`, etc.  That would probably avoid the performance issues from the previous idea.

## Revise inline parsing in 2.0 a different way

We could define a second way to implement inline parsers that aren't dependent on providing a hint to the engine about which characters they're interested in.  I don't know exactly how this would be implemented, though the ideal solution would only scan the current line of text once.

## Use an event instead?

We could fire a new event at the very start of the `InlineParserEngine::parse()` method.  This would allow us to check the entire line once before allowing the current inline parser logic to run.

---

I feel like the latter two options would give the most flexibility but we'd have to be very careful with the implementation, and would likely require some sort of intermediate AST representing the current span of text being parsed for inlines.  It's not necessarily a bad idea, just more complex.

At this point I'm just thinking out loud :)

**Comment by markcarver** [comment] 2020-06-03 14:05
Ah, I see what you're saying now. Yeah, this will have to be addressed in 2.0.

**Comment by PhHitachi** [comment] 2020-08-25 23:47
https://babelmark.github.io/?text=http://www.sub.site.org:8080/path/api.json?query=id,name,social[facebook|twitter]
https://babelmark.github.io/?text=http://username:passowrd@sub.site.org:29000/

also the [ ] having problem i think the problem is in REGEX?

**Closed** 2020-09-26 21:46 UTC
Labels: bug, pinned, spec compliance, up-for-grabs

**Comment by colinodell** [comment] 2020-09-26 21:48
The new parsing approach we're adding for 2.x successfully resolves this issue - see https://github.com/thephpleague/commonmark/commit/00649fb7bb06d133508d6e48caff7acfd9d2d849#diff-917f23b953923cd4311cd2fcf1d9e724R85

Unfortunately, a fix for 1.x won't be available since it's not simply possible under 1.x's architecture.
